apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aksservicetarik-3199"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aksservicetarik-3199"
  template:
    metadata:
      labels:
        app: "aksservicetarik-3199"
    spec:
      containers:
        - name: "aksservicetarik-3199"
          image: "rglabstarik.azurecr.io/aksservicetarik"
          ports:
          - containerPort: 80