apiVersion: v1
kind: Service
metadata:
    name: "aksservicetarik-3199"
    labels:
        app: "aksservicetarik-3199"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "aksservicetarik-3199"